#!/usr/bin/env python3
from src import *


def ttc():
    parser = get_arg_parser()
    args = parser.parse_args()

    gbl.initialize(args)

    check_existence_of_smt_file(args.smt_file)
    check_existence_of_tools(gbl.tool_list)

    cvcrunner = CVC5Runner(args.smt_file)

    cvcrunner.run_cvc5_on_smt_file()
    mapping, cnf_file = cvcrunner.parse_cvc5_output()

    # dnf_file = convert_cnf_to_dnf(cnf_file)
    dnf_file = convert_to_dnf(cnf_file)
    cubes = parse_dnf_file(dnf_file)

    final_result = process_cubes(cubes, mapping)

    log(f"Total time: {(time.time() - gbl.starttime):.3f} s")

    if gbl.logic == "lia":
        resultstr = "s mc"
    else:
        resultstr = "s vol"
    print(f"{resultstr} {final_result}")

    cleanup()


if __name__ == "__main__":
    ttc()
